User.create! email: "rakesh.verma0487@gmail.com", password: "password"
User.create! email: "rakesh@gmail.com", password: "password"
User.create! email: "verma@gmail.com", password: "password"
User.create! email: "r.verma@gmail.com", password: "password"
User.create! email: "rk.verma@gmail.com", password: "password"
User.create! email: "krishna@svasth.in", password: "password"
User.create! email: "krishna+test@svasth.in", password: "password"
User.create! email: "krishna+svasth@svasth.in", password: "password"
